name: Go osv-scanner scan

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable'
        description: 'Go version'

jobs:
  scan-vulnerabilities:
    env:
      report-file: vulnerabilities.sarif
    name: Scan vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install osv-scanner
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest

      - name: Run scan
        run: osv-scanner scan --format sarif --output ${{ env.report-file }} .
        
      - name: Upload OWASP scan results to GitHub Security tab
        # dependabot does not have write access to publish scanning results (in any case we don't want that from temporal branches)
        if: (success() || failure()) && github.actor != 'dependabot[bot]'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ env.report-file }}