name: Go osv-scanner scan

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable'
        description: 'Go version'

jobs:
  scan-vulnerabilities:
    env:
      report-file: vulnerabilities.txt
    name: Scan vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install osv-scanner
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest

      - name: Run scan
        run: osv-scanner scan --output ${{ env.report-file }} .

      - name: Show report
        if: always()
        run: cat ${{ env.report-file }}
        
      - name: Collect report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: 'osv-scanner-report'
          path: ${{ env.report-file }}
          overwrite: true
